// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkHnb5Xs2RkCG51y_Ig7HDk36ooGWFvvg',
    appId: '1:956362533804:web:fc87839d3910f4fdf72809',
    messagingSenderId: '956362533804',
    projectId: 'first-project-bd8c7',
    authDomain: 'first-project-bd8c7.firebaseapp.com',
    databaseURL: 'https://first-project-bd8c7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-project-bd8c7.firebasestorage.app',
    measurementId: 'G-C763JMS047',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5FieL10ROBchtWaI87-aHA8FwTgvclmc',
    appId: '1:956362533804:android:c6be5ee7ef33166df72809',
    messagingSenderId: '956362533804',
    projectId: 'first-project-bd8c7',
    databaseURL: 'https://first-project-bd8c7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-project-bd8c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbcrmHS_i0jyEfho6amZbSC-YGMH-vLQ0',
    appId: '1:956362533804:ios:cd47448234673440f72809',
    messagingSenderId: '956362533804',
    projectId: 'first-project-bd8c7',
    databaseURL: 'https://first-project-bd8c7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-project-bd8c7.firebasestorage.app',
    iosBundleId: 'com.example.cepuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbcrmHS_i0jyEfho6amZbSC-YGMH-vLQ0',
    appId: '1:956362533804:ios:cd47448234673440f72809',
    messagingSenderId: '956362533804',
    projectId: 'first-project-bd8c7',
    databaseURL: 'https://first-project-bd8c7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-project-bd8c7.firebasestorage.app',
    iosBundleId: 'com.example.cepuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkHnb5Xs2RkCG51y_Ig7HDk36ooGWFvvg',
    appId: '1:956362533804:web:7d725fe8ed8e5469f72809',
    messagingSenderId: '956362533804',
    projectId: 'first-project-bd8c7',
    authDomain: 'first-project-bd8c7.firebaseapp.com',
    databaseURL: 'https://first-project-bd8c7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-project-bd8c7.firebasestorage.app',
    measurementId: 'G-49FLVD6SL1',
  );
}
